site_name: MkDocs KaTeX SSR
site_url: https://raineblog.dpdns.org/mkdocs-katex-ssr/
repo_url: https://github.com/raineblog/mkdocs-katex-ssr
repo_name: raineblog/mkdocs-katex-ssr

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.view

nav:
  - Home: index.md
  - Installation: getting-started.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md
  - Demo: demo.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
  - katex-ssr:
      embed_assets: true
      katex_css_filename: "katex-swap.min.css"
      ssr_contribs:
        - mhchem
      # client_scripts:
      #   - copy-tex
      katex_options:
        macros:
          "\\RR": "\\mathbb{R}"
